-- Seed Data for Questions
insert into public.questions (category, question_text) values
('Identity', 'Who are you when no one''s watching?'),
('Identity', 'What do you believe that most people don''t?'),
('Identity', 'How has your definition of success changed over time?'),
('Identity', 'What part of yourself did you have to lose to become who you are?'),
('Identity', 'If you could tell your younger self one thing, what would it be?'),
('Identity', 'What do you know now that you wish you''d known 10 years ago?'),
('Identity', 'What are you afraid of that you don''t tell people?'),
('Identity', 'What makes you feel most alive?'),
('Identity', 'What''s the gap between who you are and who you want to be?'),
('Identity', 'What do you pretend not to care about?'),
('Relationships', 'What''s the most important thing you''ve learned about love?'),
('Relationships', 'Who shaped who you are, and how?'),
('Relationships', 'What do you wish you''d said to someone before it was too late?'),
('Legacy', 'How do you want to be remembered?'),
('Legacy', 'What matters more than you thought it would?'),
('Legacy', 'What values do you refuse to compromise on?'),
('Time', 'What moment do you keep returning to?'),
('Time', 'What era of your life do you miss most?'),
('Time', 'What does time feel like to you now?'),
('Life Lessons', 'What''s the hardest decision you''ve ever made?');
